import Head from "next/head";
import Dashbord from "../components/Dashbord";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Spotify - Dashbord</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Dashbord />
    </div>
  );
}
